[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimize_runs = 999999
via_ir = true
solc = '0.8.22'
verbosity = 2
ffi = true
fs_permissions = [
  { access = "read", path = "scripts/config.json" },
  { access = "read", path = "script/1.0.0/input.json" }
]

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts"
]

[profile.intense.fuzz]
runs = 10000
max_test_rejects = 999999

# See more config options https://github.com/foundry-rs/foundry/tree/master/config