name: Source branch check
on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  check-main:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.head_ref }} != "staging" ]; then
            echo "Merge requests to main branch are only allowed from staging branch."
            exit 1
          fi
